on: [push, pull_request]

name: tests

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tc: [1.66.0, stable, beta, nightly]
        ar:
        - --all --no-default-features
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: ${{ matrix.ar }}
  test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        tc: [1.66.0, stable, beta, nightly]
        ar:
        - --all --no-default-features
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: ${{ matrix.ar }}
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        tc: [1.66.0, stable, beta, nightly]
        ar:
        - --all --no-default-features
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: ${{ matrix.ar }}
